In [350]:
# Load libraries
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
import matplotlib.pyplot as plt
%matplotlib inline

df = pd.read_csv("/content/Malware.csv") # 30% subsample from original benign samples
df = df.drop([df.columns[0]], axis=1)
df.drop_duplicates(keep=False, inplace=True)
df.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (85) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Source.IP  Source.Port   Destination.IP  ...    Idle.Min   Label Family
0    10.42.0.151      49952.0   114.134.80.163  ...  24900000.0  ADWARE  FEIWO
1        0.0.0.0         68.0  255.255.255.255  ...         0.0  ADWARE  FEIWO
2    10.42.0.151      51550.0    172.217.1.163  ...         0.0  ADWARE  FEIWO
3    10.42.0.151      58354.0   172.217.12.142  ...         0.0  ADWARE  FEIWO
4  91.190.218.57      12350.0      10.42.0.151  ...         0.0  ADWARE  FEIWO

[5 rows x 85 columns]

In [351]:
df['Label'].value_counts()

SCAREWARE     33000
SMSMALWARE    31767
BENIGN        30447
RANSOMWARE    30000
ADWARE        29956
Name: Label, dtype: int64

In [352]:
len(df['Label'].value_counts())

5

In [353]:
df.isnull().sum()

Source.IP               0
Source.Port             0
Destination.IP          0
Destination.Port        0
Protocol                0
                    ...  
Idle.Std                0
Idle.Max                0
Idle.Min                0
Label                   0
Family              30447
Length: 85, dtype: int64

In [354]:
df.dropna(subset=['Label'], inplace=True)

In [355]:
df.Label.unique()

array(['ADWARE', 'RANSOMWARE', 'SCAREWARE', 'SMSMALWARE', 'BENIGN'],
      dtype=object)

In [356]:
df1 = df.replace(to_replace ="ADWARE", 
                 value =1.0) 
df2 = df1.replace(to_replace ="RANSOMWARE", 
                 value =2.0)
df3 = df2.replace(to_replace ="SCAREWARE", 
                 value =3.0)
df4 = df3.replace(to_replace ="SMSMALWARE", 
                 value =4.0)
df5 = df4.replace(to_replace ="BENIGN", 
                 value =0.0)

In [357]:
df5["Source.IP"] = df5["Source.IP"].str.replace(r'\D', '')
df5["Destination.IP"] = df5["Destination.IP"].str.replace(r'\D', '')
df5["Timestamp"] = df5["Timestamp"].str.replace(r'\D', '')
df6 =  df5.replace([np.inf, -np.inf], np.nan)
df7 = df6.fillna(0)
f_df = df7

In [358]:
df.Family.unique()

array(['FEIWO', 'KEMOGE', 'MOBIDASH', 'EWIND', 'KOODOUS', 'DOWGIN',
       'SELFMITE', 'SHUANET', 'GOOLIGAN', 'YOUMI', 'JISUT', 'WANNALOCKER',
       'KOLER', 'LOCKERPIN', 'SIMPLOCKER', 'SVPENG', 'CHARGER',
       'RANSOMBO', 'PLETOR', 'PORNDROID', 'ANDROIDSPY', 'AVFORANDROID',
       'AVPASS', 'ANDROIDDEFENDER', 'FAKEAPPAL', 'FAKEAPP', 'FAKEAV',
       'FAKEJOBOFFER', 'FAKETAOBAO', 'VIRUSSHIELD', 'PENETHO', 'BIIGE',
       'FAKENOTIFY', 'PLANKTON', 'SMSSNIFFER', 'FAKEINST', 'NANDROBOX',
       'JIFAKE', 'MAZARBOT', 'ZSONE', 'BEANBOT', 'FAKEMART', nan],
      dtype=object)

In [359]:
f_df1 = f_df.replace(to_replace ="FEIWO", 
                 value =1.0) 
f_df2 = f_df1.replace(to_replace ="KEMOGE", 
                 value =2.0)
f_df3 = f_df2.replace(to_replace ="MOBIDASH", 
                 value =3.0)
f_df4 = f_df3.replace(to_replace ="EWIND", 
                 value =4.0)
f_df5 = f_df4.replace(to_replace ="KOODOUS", 
                 value =5.0)
f_df6 = f_df5.replace(to_replace ="DOWGIN", 
                 value =6.0)
f_df7 = f_df6.replace(to_replace ="SELFMITE", 
                 value =7.0)
f_df8 = f_df7.replace(to_replace ="SHUANET", 
                 value =8.0)
f_df9 = f_df8.replace(to_replace ="GOOLIGAN", 
                 value =9.0)
f_df10 = f_df9.replace(to_replace ="YOUMI", 
                 value =10.0)
f_df11 = f_df10.replace(to_replace ="JISUT", 
                 value =11.0)
f_df12 = f_df11.replace(to_replace ="WANNALOCKER", 
                 value =12.0) 
f_df13 = f_df12.replace(to_replace ="KOLER", 
                 value =13.0)
f_df14 = f_df13.replace(to_replace ="LOCKERPIN", 
                 value =14.0)
f_df15 = f_df14.replace(to_replace ="SIMPLOCKER", 
                 value =15.0)
f_df16 = f_df15.replace(to_replace ="SVPENG", 
                 value =16.0)
f_df17 = f_df16.replace(to_replace ="CHARGER", 
                 value =17.0)
f_df18 = f_df17.replace(to_replace ="RANSOMBO", 
                 value =18.0)
f_df19 = f_df18.replace(to_replace ="PLETOR", 
                 value =19.0)
f_df20 = f_df19.replace(to_replace ="PORNDROID", 
                 value =20.0)
f_df21 = f_df20.replace(to_replace ="ANDROIDSPY", 
                 value =21.0)
f_df22 = f_df21.replace(to_replace ="AVFORANDROID", 
                 value =22.0)
f_df23 = f_df22.replace(to_replace ="AVPASS", 
                 value =23.0) 
f_df24 = f_df23.replace(to_replace ="ANDROIDDEFENDER", 
                 value =24.0)
f_df25 = f_df24.replace(to_replace ="FAKEAPPAL", 
                 value =25.0)
f_df26 = f_df25.replace(to_replace ="FAKEAPP", 
                 value =26.0)
f_df27 = f_df26.replace(to_replace ="FAKEAV", 
                 value =27.0)
f_df28 = f_df27.replace(to_replace ="FAKEJOBOFFER", 
                 value =28.0)
f_df29 = f_df28.replace(to_replace ="FAKETAOBAO", 
                 value =29.0)
f_df30 = f_df29.replace(to_replace ="VIRUSSHIELD", 
                 value =30.0)
f_df31 = f_df30.replace(to_replace ="PENETHO", 
                 value =31.0)
f_df32 = f_df31.replace(to_replace ="BIIGE", 
                 value =32.0)
f_df33 = f_df32.replace(to_replace ="FAKENOTIFY", 
                 value =33.0)
f_df34 = f_df33.replace(to_replace ="PLANKTON", 
                 value =34.0) 
f_df35 = f_df34.replace(to_replace ="SMSSNIFFER", 
                 value =35.0)
f_df36 = f_df35.replace(to_replace ="FAKEINST", 
                 value =36.0)
f_df37 = f_df36.replace(to_replace ="NANDROBOX", 
                 value =37.0)
f_df38 = f_df37.replace(to_replace ="JIFAKE", 
                 value =38.0)
f_df39 = f_df38.replace(to_replace ="MAZARBOT", 
                 value =39.0)
f_df40 = f_df39.replace(to_replace ="ZSONE", 
                 value =40.0)
f_df41 = f_df40.replace(to_replace ="BEANBOT", 
                 value =41.0)
f_df42 = f_df41.replace(to_replace ="FAKEMART", 
                 value =42.0)
f_df43 = f_df42.fillna(0.0)
real_df = f_df43.astype(float)

In [360]:
real_df.isnull().sum()

Source.IP           0
Source.Port         0
Destination.IP      0
Destination.Port    0
Protocol            0
                   ..
Idle.Std            0
Idle.Max            0
Idle.Min            0
Label               0
Family              0
Length: 85, dtype: int64

In [361]:
c =  real_df.drop('Label', axis=1)
a= c.drop('Family', axis=1)
b = real_df['Label']

In [362]:
#Univariate feature selection
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

In [363]:
bestfeatures = SelectKBest(score_func=f_classif, k=10)
fit = bestfeatures.fit(a,b)

/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_univariate_selection.py:114: UserWarning: Features [36 37 38 50 54 55 61 62 63 64 65 66] are constant.
  UserWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw


In [364]:
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(a.columns)

In [365]:
#concat two dataframes for better visualization 
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']  #naming the dataframe columns

In [366]:
featureScores

Specs       Score
0          Source.IP   12.573399
1        Source.Port   89.198627
2     Destination.IP  104.574873
3   Destination.Port  127.106005
4           Protocol  142.148710
..               ...         ...
78        Active.Min   39.867481
79         Idle.Mean   85.681873
80          Idle.Std   24.380698
81          Idle.Max   93.185653
82          Idle.Min   75.682306

[83 rows x 2 columns]

In [367]:
print(featureScores.nlargest(15,'Score'))  #print 15 best features

               Specs         Score
5          Timestamp  27707.365004
4           Protocol    142.148710
28       Fwd.IAT.Max    140.341282
25     Fwd.IAT.Total    129.423231
3   Destination.Port    127.106005
23      Flow.IAT.Max    115.951485
35     Fwd.PSH.Flags    114.141354
49    SYN.Flag.Count    114.141354
2     Destination.IP    104.574873
6      Flow.Duration     99.293089
27       Fwd.IAT.Std     94.692103
81          Idle.Max     93.185653
1        Source.Port     89.198627
79         Idle.Mean     85.681873
22      Flow.IAT.Std     85.226464


In [368]:
myl = featureScores.nlargest(15,'Score')['Specs']

In [369]:
X = real_df[myl]
y = real_df['Label']

In [370]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [371]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [372]:
y_pred = classifier.predict(X_test)

In [373]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import cross_val_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[5851  229    0    0    0]
 [ 228 5812    0    0    0]
 [   0    0 6053    0    0]
 [   0    0    0 5562  909]
 [   0    0    0 1037 5353]]
              precision    recall  f1-score   support

         0.0       0.96      0.96      0.96      6080
         1.0       0.96      0.96      0.96      6040
         2.0       1.00      1.00      1.00      6053
         3.0       0.84      0.86      0.85      6471
         4.0       0.85      0.84      0.85      6390

    accuracy                           0.92     31034
   macro avg       0.92      0.92      0.92     31034
weighted avg       0.92      0.92      0.92     31034



In [374]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("precision:",metrics.precision_score(y_test, y_pred,average='micro'))
print("Recall:",metrics.recall_score(y_test, y_pred,average='micro'))
print("F1-Score:",metrics.f1_score(y_test, y_pred,average='micro'))

Accuracy: 0.9225687955145969
precision: 0.9225687955145969
Recall: 0.9225687955145969
F1-Score: 0.9225687955145969


In [375]:
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
validation_accuracy = []
validation_f1 =[]
fold_and_validate = KFold(n_splits=10, shuffle=True, random_state=145)
for train_set_indices, validation_set_indices in fold_and_validate.split(X_train):
    cv_train_set = X_train.iloc[train_set_indices]
    cv_train_target = y_train.iloc[train_set_indices]
    
    cv_xvalidation = X_train.iloc[validation_set_indices]
    cv_y_true = y_train.iloc[validation_set_indices]
    cv_y_predicted = classifier.predict(cv_xvalidation)
    
    cv_accuracy_score = accuracy_score(cv_y_true, cv_y_predicted)
    cv_f1_score = f1_score(cv_y_true, cv_y_predicted,  average="weighted")
    validation_accuracy.append(cv_accuracy_score)
    validation_f1.append(cv_f1_score)
    
print("Cross validation accuracies are: ", validation_accuracy)
print("Cross validation f1 scores  are: ", validation_f1)

Cross validation accuracies are:  [0.9963750604156597, 0.996697277267601, 0.9956500724987917, 0.995730626711777, 0.9970194941195425, 0.995730626711777, 0.996294207685491, 0.9966970111979376, 0.9957302827680657, 0.9961330862805123]
Cross validation f1 scores  are:  [0.9963740287636405, 0.996696659167164, 0.9956488214358477, 0.9957292213894661, 0.9970189280269249, 0.9957301493937114, 0.996292964552675, 0.996696487940827, 0.9957286272822201, 0.9961323756230006]


In [376]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

In [377]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import multilabel_confusion_matrix
#print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.95      0.99      0.97      6080
         1.0       0.97      0.95      0.96      6040
         2.0       0.97      0.96      0.96      6053
         3.0       0.83      0.85      0.84      6471
         4.0       0.86      0.83      0.85      6390

    accuracy                           0.91     31034
   macro avg       0.92      0.92      0.92     31034
weighted avg       0.91      0.91      0.91     31034



In [378]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("precision:",metrics.precision_score(y_test, y_pred,average='micro'))
print("Recall:",metrics.recall_score(y_test, y_pred,average='micro'))
print("F1-Score:",metrics.f1_score(y_test, y_pred,average='micro'))

Accuracy: 0.9147386737127022
precision: 0.9147386737127022
Recall: 0.9147386737127022
F1-Score: 0.9147386737127022


In [379]:
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
validation_accuracy = []
validation_f1 =[]
fold_and_validate = KFold(n_splits=10, shuffle=True, random_state=145)
for train_set_indices, validation_set_indices in fold_and_validate.split(X_train):
    cv_train_set = X_train.iloc[train_set_indices]
    cv_train_target = y_train.iloc[train_set_indices]
    
    cv_xvalidation = X_train.iloc[validation_set_indices]
    cv_y_true = y_train.iloc[validation_set_indices]
    cv_y_predicted = clf.predict(cv_xvalidation)
    
    cv_accuracy_score = accuracy_score(cv_y_true, cv_y_predicted)
    cv_f1_score = f1_score(cv_y_true, cv_y_predicted,  average="weighted")
    validation_accuracy.append(cv_accuracy_score)
    validation_f1.append(cv_f1_score)
    
print("Cross validation accuracies are: ", validation_accuracy)
print("Cross validation f1 scores  are: ", validation_f1)

Cross validation accuracies are:  [0.995972289350733, 0.9970194941195425, 0.9958111809247624, 0.9964556146286451, 0.9966167230546158, 0.995730626711777, 0.9962136469830017, 0.996052525578023, 0.9961330862805123, 0.996052525578023]
Cross validation f1 scores  are:  [0.9959726045390707, 0.9970195652276436, 0.9958113870131997, 0.9964558158014318, 0.9966168266328659, 0.9957306223687942, 0.9962137142513927, 0.9960528080074718, 0.9961329301657174, 0.9960525664805187]


In [380]:
from sklearn.neighbors import KNeighborsClassifier

#Create KNN Classifier
knn = KNeighborsClassifier(n_neighbors=10)

#Train the model using the training sets
knn.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = knn.predict(X_test)

In [381]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[6073    7    0    0    0]
 [ 281 5757    0    0    2]
 [   0    0 6053    0    0]
 [   0    0    0 5696  775]
 [   6    4    0  888 5492]]
              precision    recall  f1-score   support

         0.0       0.95      1.00      0.98      6080
         1.0       1.00      0.95      0.98      6040
         2.0       1.00      1.00      1.00      6053
         3.0       0.87      0.88      0.87      6471
         4.0       0.88      0.86      0.87      6390

    accuracy                           0.94     31034
   macro avg       0.94      0.94      0.94     31034
weighted avg       0.94      0.94      0.94     31034



In [382]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("precision:",metrics.precision_score(y_test, y_pred,average='micro'))
print("Recall:",metrics.recall_score(y_test, y_pred,average='micro'))
print("F1-Score:",metrics.f1_score(y_test, y_pred,average='micro'))

Accuracy: 0.9367467938390153
precision: 0.9367467938390153
Recall: 0.9367467938390153
F1-Score: 0.9367467938390153


In [383]:
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
validation_accuracy = []
validation_f1 =[]
fold_and_validate = KFold(n_splits=10, shuffle=True, random_state=145)
for train_set_indices, validation_set_indices in fold_and_validate.split(X_train):
    cv_train_set = X_train.iloc[train_set_indices]
    cv_train_target = y_train.iloc[train_set_indices]
    
    cv_xvalidation = X_train.iloc[validation_set_indices]
    cv_y_true = y_train.iloc[validation_set_indices]
    cv_y_predicted = knn.predict(cv_xvalidation)
    
    cv_accuracy_score = accuracy_score(cv_y_true, cv_y_predicted)
    cv_f1_score = f1_score(cv_y_true, cv_y_predicted,  average="weighted")
    validation_accuracy.append(cv_accuracy_score)
    validation_f1.append(cv_f1_score)
    
print("Cross validation accuracies are: ", validation_accuracy)
print("Cross validation f1 scores  are: ", validation_f1)

Cross validation accuracies are:  [0.9483647494763976, 0.9459481230868374, 0.9449814725310134, 0.9465120025777348, 0.9493314000322217, 0.9424842919284678, 0.9439297510674293, 0.944090872472408, 0.9428824619350681, 0.9461854507371305]
Cross validation f1 scores  are:  [0.9483280046542442, 0.945900988498243, 0.9449400753444028, 0.9464840488047416, 0.9493157934035397, 0.9424592502395729, 0.9439038598728091, 0.9440608764732235, 0.9428509899156503, 0.9461437706470972]


In [384]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = gnb.predict(X_test)

In [385]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[5640    0    0  440    0]
 [ 312 5728    0    0    0]
 [   0    0 4480 1573    0]
 [   0    0 4892 1390  189]
 [ 881 1046 2282  237 1944]]
              precision    recall  f1-score   support

         0.0       0.83      0.93      0.87      6080
         1.0       0.85      0.95      0.89      6040
         2.0       0.38      0.74      0.51      6053
         3.0       0.38      0.21      0.27      6471
         4.0       0.91      0.30      0.46      6390

    accuracy                           0.62     31034
   macro avg       0.67      0.63      0.60     31034
weighted avg       0.67      0.62      0.60     31034



In [386]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("precision:",metrics.precision_score(y_test, y_pred,average='micro'))
print("Recall:",metrics.recall_score(y_test, y_pred,average='micro'))
print("F1-Score:",metrics.f1_score(y_test, y_pred,average='micro'))

Accuracy: 0.6180962814977122
precision: 0.6180962814977122
Recall: 0.6180962814977122
F1-Score: 0.6180962814977122


In [387]:
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
validation_accuracy = []
validation_f1 =[]
fold_and_validate = KFold(n_splits=10, shuffle=True, random_state=145)
for train_set_indices, validation_set_indices in fold_and_validate.split(X_train):
    cv_train_set = X_train.iloc[train_set_indices]
    cv_train_target = y_train.iloc[train_set_indices]
    
    cv_xvalidation = X_train.iloc[validation_set_indices]
    cv_y_true = y_train.iloc[validation_set_indices]
    cv_y_predicted = gnb.predict(cv_xvalidation)
    
    cv_accuracy_score = accuracy_score(cv_y_true, cv_y_predicted)
    cv_f1_score = f1_score(cv_y_true, cv_y_predicted,  average="weighted")
    validation_accuracy.append(cv_accuracy_score)
    validation_f1.append(cv_f1_score)
    
print("Cross validation accuracies are: ", validation_accuracy)
print("Cross validation f1 scores  are: ", validation_f1)

Cross validation accuracies are:  [0.6091509585951346, 0.6133397776703722, 0.621395198968906, 0.6187369099403899, 0.6142258740132109, 0.6210729821169647, 0.6100056392491743, 0.6117779747039395, 0.6144364778860871, 0.6232175944574236]
Cross validation f1 scores  are:  [0.5876647802584687, 0.5915778297538951, 0.6005743317927187, 0.5976182147545559, 0.5924839371507401, 0.5996449047587753, 0.586197763343962, 0.5915790410092824, 0.5913389475923169, 0.6018446319050438]


In [388]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn import model_selection

model_sgb = GradientBoostingClassifier(n_estimators=100, random_state=10)
model_sgb.fit(X_train,y_train)
y_pred = model_sgb.predict(X_test)

In [389]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[6080    0    0    0    0]
 [ 312 5728    0    0    0]
 [   0    0 6053    0    0]
 [   0    0    0 5534  937]
 [   0    0    0  591 5799]]
              precision    recall  f1-score   support

         0.0       0.95      1.00      0.97      6080
         1.0       1.00      0.95      0.97      6040
         2.0       1.00      1.00      1.00      6053
         3.0       0.90      0.86      0.88      6471
         4.0       0.86      0.91      0.88      6390

    accuracy                           0.94     31034
   macro avg       0.94      0.94      0.94     31034
weighted avg       0.94      0.94      0.94     31034



In [390]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("precision:",metrics.precision_score(y_test, y_pred,average='micro'))
print("Recall:",metrics.recall_score(y_test, y_pred,average='micro'))
print("F1-Score:",metrics.f1_score(y_test, y_pred,average='micro'))

Accuracy: 0.9407101888251596
precision: 0.9407101888251596
Recall: 0.9407101888251596
F1-Score: 0.9407101888251596


In [391]:
from sklearn.model_selection import KFold
validation_accuracy = []
validation_f1 =[]
fold_and_validate = KFold(n_splits=10, shuffle=True, random_state=145)
for train_set_indices, validation_set_indices in fold_and_validate.split(X_train):
    cv_train_set = X_train.iloc[train_set_indices]
    cv_train_target = y_train.iloc[train_set_indices]
    
    cv_xvalidation = X_train.iloc[validation_set_indices]
    cv_y_true = y_train.iloc[validation_set_indices]
    cv_y_predicted = model_sgb.predict(cv_xvalidation)
    
    cv_accuracy_score = accuracy_score(cv_y_true, cv_y_predicted)
    cv_f1_score = f1_score(cv_y_true, cv_y_predicted,  average="weighted")
    validation_accuracy.append(cv_accuracy_score)
    validation_f1.append(cv_f1_score)
    
print("Cross validation accuracies are: ", validation_accuracy)
print("Cross validation f1 scores  are: ", validation_f1)

Cross validation accuracies are:  [0.9406315450298051, 0.9381343644272595, 0.9396648944739809, 0.9406315450298051, 0.94417593040116, 0.9380538102142743, 0.9370015306533473, 0.9356319987110288, 0.9370820913558366, 0.9414323692902602]
Cross validation f1 scores  are:  [0.9406256494860805, 0.938119692542152, 0.9396509786354906, 0.9406267204046758, 0.9441641427384806, 0.937986622887227, 0.9369923486722186, 0.93561118900033, 0.9370744549607666, 0.9414050109829782]


In [392]:
print("From here we will calculate what type of family it is")

From here we will calculate what type of family it is


In [393]:
c =  real_df.drop('Family', axis=1)
a = c.drop('Label', axis=1)
b = real_df['Family']

In [394]:
#Univariate feature selection
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

In [395]:
bestfeatures = SelectKBest(score_func=f_classif, k=10)
fit = bestfeatures.fit(a,b)

/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_univariate_selection.py:114: UserWarning: Features [36 37 38 50 54 55 61 62 63 64 65 66] are constant.
  UserWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw


In [396]:
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(a.columns)

In [397]:
#concat two dataframes for better visualization 
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']  #naming the dataframe columns

In [398]:
featureScores

Specs       Score
0          Source.IP    3.717381
1        Source.Port   75.443928
2     Destination.IP   31.737510
3   Destination.Port  112.372103
4           Protocol   60.243414
..               ...         ...
78        Active.Min   25.007062
79         Idle.Mean   15.065311
80          Idle.Std   10.424493
81          Idle.Max   16.280284
82          Idle.Min   13.794595

[83 rows x 2 columns]

In [399]:
print(featureScores.nlargest(15,'Score'))  #print 15 best features

                     Specs         Score
5                Timestamp  18171.683898
3         Destination.Port    112.372103
1              Source.Port     75.443928
77              Active.Max     67.871427
4                 Protocol     60.243414
76              Active.Std     50.482767
75             Active.Mean     48.185440
21           Flow.IAT.Mean     45.492261
25           Fwd.IAT.Total     39.517956
23            Flow.IAT.Max     38.815642
26            Fwd.IAT.Mean     37.702217
43       Min.Packet.Length     37.423610
71  Init_Win_bytes_forward     36.716249
6            Flow.Duration     35.611764
28             Fwd.IAT.Max     35.079394


In [400]:
myl = featureScores.nlargest(15,'Score')['Specs']

In [401]:
X = real_df[myl]
y = real_df['Family']

In [402]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [403]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [404]:
y_pred = classifier.predict(X_test)

In [405]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import cross_val_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[5838  159    0 ...    0    0    0]
 [ 177  166   39 ...    0    0    0]
 [   0   39  374 ...    0    0    0]
 ...
 [   0    0    0 ...  590    0    0]
 [   0    0    0 ...    0  160    2]
 [   0    0    0 ...    0    1  449]]
              precision    recall  f1-score   support

         0.0       0.95      0.95      0.95      6115
         1.0       0.27      0.27      0.27       621
         2.0       0.63      0.64      0.64       582
         3.0       0.31      0.32      0.32       607
         4.0       0.52      0.50      0.51       595
         5.0       0.29      0.30      0.30       600
         6.0       0.38      0.41      0.39       593
         7.0       0.50      0.46      0.48       635
         8.0       0.34      0.34      0.34       607
         9.0       0.50      0.49      0.50       585
        10.0       0.55      0.57      0.56       616
        11.0       0.66      0.64      0.65       600
        12.0       0.52      0.54      0.53       600
        13.0   

In [406]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("precision:",metrics.precision_score(y_test, y_pred,average='micro'))
print("Recall:",metrics.recall_score(y_test, y_pred,average='micro'))
print("F1-Score:",metrics.f1_score(y_test, y_pred,average='micro'))

Accuracy: 0.5870657988013147
precision: 0.5870657988013147
Recall: 0.5870657988013147
F1-Score: 0.5870657988013147


In [407]:
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
validation_accuracy = []
validation_f1 =[]
fold_and_validate = KFold(n_splits=10, shuffle=True, random_state=145)
for train_set_indices, validation_set_indices in fold_and_validate.split(X_train):
    cv_train_set = X_train.iloc[train_set_indices]
    cv_train_target = y_train.iloc[train_set_indices]
    
    cv_xvalidation = X_train.iloc[validation_set_indices]
    cv_y_true = y_train.iloc[validation_set_indices]
    cv_y_predicted = classifier.predict(cv_xvalidation)
    
    cv_accuracy_score = accuracy_score(cv_y_true, cv_y_predicted)
    cv_f1_score = f1_score(cv_y_true, cv_y_predicted,  average="weighted")
    validation_accuracy.append(cv_accuracy_score)
    validation_f1.append(cv_f1_score)
    
print("Cross validation accuracies are: ", validation_accuracy)
print("Cross validation f1 scores  are: ", validation_f1)

Cross validation accuracies are:  [0.9900918318028032, 0.9898501691638473, 0.9913806992105687, 0.990736265506686, 0.9904140486547447, 0.9920251329144514, 0.9912994441311528, 0.9919439297510674, 0.9895271086763877, 0.9912188834286635]
Cross validation f1 scores  are:  [0.9901315177008129, 0.9898838710746118, 0.9914209898848462, 0.9907859163693786, 0.9904606220926877, 0.9920237993802855, 0.9913057434854621, 0.9919454355688053, 0.9895317144928283, 0.9912201700070387]


In [408]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

In [409]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import multilabel_confusion_matrix
#print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.92      1.00      0.96      6115
         1.0       0.40      0.18      0.25       621
         2.0       0.65      0.70      0.68       582
         3.0       0.34      0.36      0.35       607
         4.0       0.57      0.58      0.57       595
         5.0       0.33      0.28      0.31       600
         6.0       0.42      0.40      0.41       593
         7.0       0.51      0.53      0.52       635
         8.0       0.39      0.42      0.40       607
         9.0       0.66      0.50      0.57       585
        10.0       0.51      0.64      0.57       616
        11.0       0.68      0.74      0.71       600
        12.0       0.54      0.48      0.51       600
        13.0       0.66      0.65      0.65       652
        14.0       0.56      0.60      0.58       579
        15.0       0.50      0.43      0.47       599
        16.0       0.41      0.37      0.39       607
        17.0       0.46    

In [410]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("precision:",metrics.precision_score(y_test, y_pred,average='micro'))
print("Recall:",metrics.recall_score(y_test, y_pred,average='micro'))
print("F1-Score:",metrics.f1_score(y_test, y_pred,average='micro'))

Accuracy: 0.5955403750725011
precision: 0.5955403750725011
Recall: 0.5955403750725011
F1-Score: 0.5955403750725011


In [411]:
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
validation_accuracy = []
validation_f1 =[]
fold_and_validate = KFold(n_splits=10, shuffle=True, random_state=145)
for train_set_indices, validation_set_indices in fold_and_validate.split(X_train):
    cv_train_set = X_train.iloc[train_set_indices]
    cv_train_target = y_train.iloc[train_set_indices]
    
    cv_xvalidation = X_train.iloc[validation_set_indices]
    cv_y_true = y_train.iloc[validation_set_indices]
    cv_y_predicted = clf.predict(cv_xvalidation)
    
    cv_accuracy_score = accuracy_score(cv_y_true, cv_y_predicted)
    cv_f1_score = f1_score(cv_y_true, cv_y_predicted,  average="weighted")
    validation_accuracy.append(cv_accuracy_score)
    validation_f1.append(cv_f1_score)
    
print("Cross validation accuracies are: ", validation_accuracy)
print("Cross validation f1 scores  are: ", validation_f1)

Cross validation accuracies are:  [0.9908973739326566, 0.9898501691638473, 0.9919445787014661, 0.9910584823586274, 0.990977928145642, 0.9918640244884808, 0.9904132764037702, 0.9903327157012809, 0.9904938371062596, 0.9905743978087489]
Cross validation f1 scores  are:  [0.9909035049757844, 0.9898621712506622, 0.9919209890703524, 0.9910267551103995, 0.9910036684745337, 0.9918515918296953, 0.9904193659405442, 0.9903064343444384, 0.9904960534793282, 0.9905861792912253]


In [412]:
from sklearn.neighbors import KNeighborsClassifier

#Create KNN Classifier
knn = KNeighborsClassifier(n_neighbors=10)

#Train the model using the training sets
knn.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = knn.predict(X_test)

In [413]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[6111    4    0 ...    0    0    0]
 [ 198  160   40 ...    0    0    0]
 [   0   17  397 ...    0    0    0]
 ...
 [   0    0    0 ...  590    0    0]
 [   0    0    0 ...    0  200    2]
 [   0    0    0 ...    0    0  377]]
              precision    recall  f1-score   support

         0.0       0.95      1.00      0.97      6115
         1.0       0.50      0.26      0.34       621
         2.0       0.60      0.68      0.64       582
         3.0       0.30      0.35      0.32       607
         4.0       0.58      0.52      0.55       595
         5.0       0.37      0.32      0.34       600
         6.0       0.34      0.35      0.35       593
         7.0       0.46      0.53      0.49       635
         8.0       0.39      0.27      0.32       607
         9.0       0.62      0.51      0.56       585
        10.0       0.54      0.64      0.59       616
        11.0       0.69      0.82      0.75       600
        12.0       0.59      0.50      0.54       600
        13.0   

In [414]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("precision:",metrics.precision_score(y_test, y_pred,average='micro'))
print("Recall:",metrics.recall_score(y_test, y_pred,average='micro'))
print("F1-Score:",metrics.f1_score(y_test, y_pred,average='micro'))

Accuracy: 0.6200296449055874
precision: 0.6200296449055874
Recall: 0.6200296449055874
F1-Score: 0.6200296449055874


In [415]:
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
validation_accuracy = []
validation_f1 =[]
fold_and_validate = KFold(n_splits=10, shuffle=True, random_state=145)
for train_set_indices, validation_set_indices in fold_and_validate.split(X_train):
    cv_train_set = X_train.iloc[train_set_indices]
    cv_train_target = y_train.iloc[train_set_indices]
    
    cv_xvalidation = X_train.iloc[validation_set_indices]
    cv_y_true = y_train.iloc[validation_set_indices]
    cv_y_predicted = knn.predict(cv_xvalidation)
    
    cv_accuracy_score = accuracy_score(cv_y_true, cv_y_predicted)
    cv_f1_score = f1_score(cv_y_true, cv_y_predicted,  average="weighted")
    validation_accuracy.append(cv_accuracy_score)
    validation_f1.append(cv_f1_score)
    
print("Cross validation accuracies are: ", validation_accuracy)
print("Cross validation f1 scores  are: ", validation_f1)

Cross validation accuracies are:  [0.6921217979700338, 0.6915579184791365, 0.6878524246818108, 0.6980022555179636, 0.7016271951023039, 0.6962300628322862, 0.6960444695077741, 0.704181100459196, 0.6942721340530089, 0.6924997985982437]
Cross validation f1 scores  are:  [0.6873353581858676, 0.687196878656821, 0.6827382084098814, 0.6935343649416014, 0.6968393114289007, 0.6916135799800591, 0.6906018041799692, 0.6993439912898589, 0.688820691193406, 0.6872484174478433]


In [416]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = gnb.predict(X_test)

In [417]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[6115    0    0 ...    0    0    0]
 [ 225    0  118 ...    0    0    0]
 [   0    0  582 ...    0    0    0]
 ...
 [ 590    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    2]
 [   0    0    0 ...    0    0  260]]
              precision    recall  f1-score   support

         0.0       0.83      1.00      0.91      6115
         1.0       0.00      0.00      0.00       621
         2.0       0.47      1.00      0.64       582
         3.0       0.00      0.00      0.00       607
         4.0       0.00      0.00      0.00       595
         5.0       0.00      0.00      0.00       600
         6.0       0.00      0.00      0.00       593
         7.0       0.22      1.00      0.36       635
         8.0       0.00      0.00      0.00       607
         9.0       0.00      0.00      0.00       585
        10.0       0.40      1.00      0.57       616
        11.0       0.64      0.52      0.58       600
        12.0       0.37      0.35      0.36       600
        13.0   

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [418]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("precision:",metrics.precision_score(y_test, y_pred,average='micro'))
print("Recall:",metrics.recall_score(y_test, y_pred,average='micro'))
print("F1-Score:",metrics.f1_score(y_test, y_pred,average='micro'))

Accuracy: 0.4442224656827995
precision: 0.4442224656827995
Recall: 0.4442224656827995
F1-Score: 0.44422246568279944


In [419]:
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
validation_accuracy = []
validation_f1 =[]
fold_and_validate = KFold(n_splits=10, shuffle=True, random_state=145)
for train_set_indices, validation_set_indices in fold_and_validate.split(X_train):
    cv_train_set = X_train.iloc[train_set_indices]
    cv_train_target = y_train.iloc[train_set_indices]
    
    cv_xvalidation = X_train.iloc[validation_set_indices]
    cv_y_true = y_train.iloc[validation_set_indices]
    cv_y_predicted = gnb.predict(cv_xvalidation)
    
    cv_accuracy_score = accuracy_score(cv_y_true, cv_y_predicted)
    cv_f1_score = f1_score(cv_y_true, cv_y_predicted,  average="weighted")
    validation_accuracy.append(cv_accuracy_score)
    validation_f1.append(cv_f1_score)
    
print("Cross validation accuracies are: ", validation_accuracy)
print("Cross validation f1 scores  are: ", validation_f1)

Cross validation accuracies are:  [0.43861768970517157, 0.4483647494763976, 0.4360399548896407, 0.43531496697277267, 0.44288706299339453, 0.44409537618817463, 0.44268106017884473, 0.44324498509627, 0.43551115765729476, 0.4371223717070813]
Cross validation f1 scores  are:  [0.34479399546567996, 0.35228169462390296, 0.3382266048375607, 0.34107070567873027, 0.3479497639670539, 0.35072284955262156, 0.34702132266349894, 0.3481001846712641, 0.3403745067814878, 0.3427714383636738]


In [420]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn import model_selection

model_sgb = GradientBoostingClassifier(n_estimators=100, random_state=10)
model_sgb.fit(X_train,y_train)
y_pred = model_sgb.predict(X_test)

In [421]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[6114    1    0 ...    0    0    0]
 [ 224   22   44 ...    0    0    0]
 [   0    0  390 ...    0    0    0]
 ...
 [   0    0    0 ...  590    0    0]
 [   0    0    0 ...    0  294    0]
 [   0    0    0 ...    0    0  431]]
              precision    recall  f1-score   support

         0.0       0.95      1.00      0.97      6115
         1.0       0.47      0.04      0.07       621
         2.0       0.59      0.67      0.63       582
         3.0       0.38      0.14      0.20       607
         4.0       0.54      0.53      0.54       595
         5.0       0.61      0.14      0.23       600
         6.0       0.39      0.64      0.48       593
         7.0       0.47      0.80      0.59       635
         8.0       0.37      0.30      0.33       607
         9.0       0.68      0.47      0.56       585
        10.0       0.49      0.86      0.62       616
        11.0       0.63      0.92      0.75       600
        12.0       0.67      0.26      0.38       600
        13.0   

In [422]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("precision:",metrics.precision_score(y_test, y_pred,average='micro'))
print("Recall:",metrics.recall_score(y_test, y_pred,average='micro'))
print("F1-Score:",metrics.f1_score(y_test, y_pred,average='micro'))

Accuracy: 0.6225107946123606
precision: 0.6225107946123606
Recall: 0.6225107946123606
F1-Score: 0.6225107946123606


In [423]:
from sklearn.model_selection import KFold
validation_accuracy = []
validation_f1 =[]
fold_and_validate = KFold(n_splits=10, shuffle=True, random_state=145)
for train_set_indices, validation_set_indices in fold_and_validate.split(X_train):
    cv_train_set = X_train.iloc[train_set_indices]
    cv_train_target = y_train.iloc[train_set_indices]
    
    cv_xvalidation = X_train.iloc[validation_set_indices]
    cv_y_true = y_train.iloc[validation_set_indices]
    cv_y_predicted = model_sgb.predict(cv_xvalidation)
    
    cv_accuracy_score = accuracy_score(cv_y_true, cv_y_predicted)
    cv_f1_score = f1_score(cv_y_true, cv_y_predicted,  average="weighted")
    validation_accuracy.append(cv_accuracy_score)
    validation_f1.append(cv_f1_score)
    
print("Cross validation accuracies are: ", validation_accuracy)
print("Cross validation f1 scores  are: ", validation_f1)

Cross validation accuracies are:  [0.6472531013371999, 0.6506363782825841, 0.6493475108748188, 0.652730787820203, 0.6554696310617045, 0.652730787820203, 0.6510110368162411, 0.6575364537178764, 0.6489970192540079, 0.6537501007008781]
Cross validation f1 scores  are:  [0.6221055903764463, 0.6247708327942855, 0.6212451274499059, 0.628735083756193, 0.6298108551258464, 0.6267796334864244, 0.6238797869142584, 0.6327232429643704, 0.6229955202857603, 0.6275491904752766]
